package cherry.model;

import cherry.model.base.BaseBaby;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Baby extends BaseBaby<Baby> {
	public static final Baby dao = new Baby();
}
